### ISSUE TITLE
Support rendering external links on index and display options

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/intraweb#34]
## Overview

We wan to support external references from indexes. The current use case is "link external procedure templates". We also want to enable some simple configuration. Since these are two different things, but we also want efficiency, we will use a single `inputs.yaml` per directory and `site-inputs.yaml` global file.

## Deliverables

- [x] support per directory `inputs.yaml` which can set display options and create links to mixed with documents, subsections, or create new sections. See [notes](#notes) for structure.
- [x] support `display.linkSection: "Documents"` (note future option to create new sections such as 'reference' and 'bibliography', etc.)
- [x] support `display.sectionOrder: [ "Documents", "Subsections" ]` and vice-a-versa; non-defined sections will be displayed in alphabetical order
- [x] support `display.sectionTitles { Documents: "Documents", Subsections: "Subsections" }` (<- default)
- [x] links are sorted alphabetically by label

## Notes

```yaml
--- # inputs.yaml (or site-inptuts.yaml) example
display:
  linkSection: document
links:
- label: A separate reference link
  url: https://google.com
  section: Reference
- label: Reddit link in documents section
  url: https://reddit.com
- label: internal link; like a cross-reference
  url: ../../foo/A Doc.md

```
